# Generated by Django 4.2.1 on 2023-06-05 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='date_of_birth',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userartist',
            name='date_of_birth',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
