# Generated by Django 4.2.1 on 2023-06-07 07:26

import enumfields.fields
from django.db import migrations

import artist.enums


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0003_alter_artist_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userartist',
            name='gender',
            field=enumfields.fields.EnumField(default='Male', enum=artist.enums.GenderChoice, max_length=10),
        ),
    ]
