# Generated by Django 4.2.1 on 2023-06-07 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0004_alter_userartist_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userartist',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
